const fs = require('fs');
const file = 'app/actions/student.ts';
let code = fs.readFileSync(file, 'utf8');

// The lines were duplicated like this:
// const parentName = ...
// const parentEmail = ...
// const parentContact = ...
// const parentEmail = ...
// const parentContact = ...

// I'll just use regex to remove duplicates.
code = code.replace(/const parentEmail = parentDoc.data\(\)\?\.email \|\| "";\s+const parentContact = parentDoc.data\(\)\?\.contact_number \|\| "";/g, '');

fs.writeFileSync(file, code);
